### PR TITLE
update readme with tracing using GraphQLContext map

### PR DESCRIPTION
**Pull request by dariuszkuc**
Updating README with information on how to use `FederatedTracingInstrumentation` together with `GraphQLContext` map.

### CODE REVIEW

**Comment by martinbonnin** [comment]
Thanks for sending this! Looks good to me. More general question/observation: are there use cases that require "Custom GraphQL context" ? I was under the impression that everything was possible using `GraphQLContext` and it's a more future proof way to do it ?

**Comment by dariuszkuc** [comment]
@martinbonnin besides support for "legacy" way as some apps may not be able to quickly update, I don't think there are any reasons to continue using custom context. I am planning to drop support for legacy deprecated context in the next major version of `graphql-kotlin`.

**Comment by martinbonnin** [comment]
In that case, I'd happily remove "Custom GraphQL context" from the docs? New users can use `GraphQLContext` and legacy users can keep using "Custom GraphQL context" but no need to advertise it much? @sachindshinde any thoughts?

**Comment by sachindshinde** [comment]
@martinbonnin That sounds fine to me (especially since there's no reasons for new users to use the deprecated custom GraphQL context).

**Comment by martinbonnin** [comment]
@dariuszkuc is that ok with you? If yes, do you mind removing the section alltogether?

**Comment by dariuszkuc** [comment]
Dropped deprecated context usage from readme.

**Review by martinbonnin — APPROVED** [review]

**Pull request merged**
