### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by rkudryashov**
Hi,

There was a discussion with @trevor-scheer (https://github.com/apollographql/apollo-server/pull/3777), and I realized that it makes sense to try this PR, or at least get feedback on it.

In the PR I tried to address https://github.com/apollographql/federation-jvm/issues/44, and also did a lot of other things. If in general it looks good to you, I will remove fork-specific and other unneeded changes.

### CODE REVIEW

**Comment by trevor-scheer** [comment]
Thanks for opening this @rkudryashov! I'm afraid this may be tough to review as-is given the number of changes. 

This may be too much of an ask, but if you're able to separate some changes into smaller PRs with explanations of what and why, that would go a long way for reviewability. Pinging @glasser and @sachindshinde so they can chime in as well if they feel differently.

**Comment by sachindshinde** [comment]
Thanks for the contributions @rkudryashov !

I'm down to review, but it would definitely help speed up the review process to separate the sets of changes into different PRs (with explanations of those changes where possible).

**Comment by rkudryashov** [comment]
If so, let's start: https://github.com/apollographql/federation-jvm/pull/48

**Comment by sachindshinde** [comment]
Closing this out, as downstream branch has been deleted. Thanks for the contributions regardless, hopefully we can integrate some of these in later.

**Pull request closed without merging**
